### ISSUE TITLE
add condition

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#1]
I completely love the idea. Unfortunatley wif you are not alone at home there are more conditons than being alone. But also watchig tv for example should avoid turning on the light automation.

Do you think adding conditions would be doable?

Would be then 100% great :)

**Comment by evildad** [comment]
You could use the undocumented feature:

`disable_switch_entity: input_boolean.foo` inside the room.definition.
If the input.boolean is false the automation in that specific room is disabled.
So watching TV sets the input.boolean.foo to false and no more automated lights.

**Comment by thundergreen** [comment]
Like this?

```
livingroom:
  module: automoli
  class: AutoMoLi
  room: livingroom
  disable_switch_entity: input_boolean.foo
  delay: 600
  daytimes:
    - { starttime: "05:30", name: morning, light: "Morning" }
    - { starttime: "07:30", name: day, light: "Working" }
    - { starttime: "20:30", name: evening, light: 90 }
    - { starttime: "22:30", name: night, light: 20 }
    - { starttime: "23:30", name: more_night, light: 0 }
  humidity_threshold: 75
  lights:
    - light.livingroom
  motion:
    - binary_sensor.motion_sensor_153d000224f421
    - binary_sensor.motion_sensor_128d4101b95fb7
  humidity:
    - sensor.humidity_128d4101b95fb7
```
What would be nice would be adding luminance directly as a blocker also.

Let's say blocker would be:

hunidity, luminance and input boolean as a general switch. What do you think?

**Comment by benleb** [comment]
Yes exactly like this :)
But yeah, luminance is already implemented but needs a little more testing ;)

**Comment by benleb** [comment]
https://github.com/benleb/ad-automoli/releases/tag/v0.4.6
illumination sensors added and as mentioned by @evildad already, a custom "disable switch" can be accomplished, with a home assistant *input_boolean* or a template sensor :)

**Comment by thundergreen** [comment]
Great! will test that :)

**Comment by thundergreen** [comment]
I have a question.I MUST rename all my entities zu get this working right? That's a bit strange I think. Because it won't find my humidity sensor or illumination .. mine are called like:

```sensor.luminance_dressing``` and ``` sensor.humidity_dressing``` etc

**Comment by thundergreen** [comment]
If I read well the docs... then I can keep my naming but have to defie the sensors manually:

```
livingroom:
  module: automoli
  class: AutoMoLi
  room: livingroom
  disable_switch_entity: input_boolean.automoli
  delay: 600
  daytimes:
    - { starttime: "05:30", name: morning, light: "Morning" }
    - { starttime: "07:30", name: day, light: "Working" }
    - { starttime: "20:30", name: evening, light: 90 }
    - { starttime: "22:30", name: night, light: 20 }
    - { starttime: "23:30", name: more_night, light: 0 }
  illuminance_threshold: 100
  lights:
    - light.livingroom
  motion:
    - binary_sensor.motion_sensor_153d000224f421
    - binary_sensor.motion_sensor_128d4101b95fb7
  humidity:
    - sensor.humidity_128d4101b95fb7
 illuminance:
  - sensor.luminance_living_room
```

Would that be ok? I mean to define illuminance? ``` illuminance: sensor.xxxxxx```
