### ISSUE TITLE
light turn on by motion off state_change?

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#12]
I could nnow get the app running but apparently it listens really to each state chage but not only "on" state change to turn on the light.

if motion is detected light turns on.. after timer off and on again and then off again after the timer :/

**Comment by thundergreen** [comment]
my config:

```
stairs_day:
  module: automoli
  class: AutoMoLi
  room: stairs
  delay: 30
  daytimes:
    - { starttime: "05:30", name: morning, light: 0}
    - { starttime: "07:45", name: day, light: 10 }
    - { starttime: "20:30", name: evening, light: 15 }
    - { starttime: "22:30", name: night, light: 0 }
    - { starttime: "23:30", name: more_night, light: 0 }
  illuminance_threshold: 100
  illuminance: 
    - sensor.average_luminance_stairs
  lights:
    - light.spots_stairs
  motion:
    - binary_sensor.motion_downstairs
    - binary_sensor.motion_upstairs
  motion_event: state_changed

stairs_night:
  module: automoli
  class: AutoMoLi
  room: stairs
  delay: 30
  daytimes:
    - { starttime: "05:30", name: morning, light: 100}
    - { starttime: "07:45", name: day, light: 0 }
    - { starttime: "20:30", name: evening, light: 0 }
    - { starttime: "22:30", name: night, light: 100 }
    - { starttime: "23:30", name: more_night, light: 100 }
  illuminance_threshold: 100
  illuminance: 
    - sensor.average_luminance_stairs
  lights:
    - light.xiaomi_gateway
  motion:
    - binary_sensor.motion_downstairs
    - binary_sensor.motion_upstairs
  motion_event: state_changed
```

**Comment by thundergreen** [comment]
this one has no issues:

```
dressing:
  module: automoli
  class: AutoMoLi
  room: dressing
  disable_switch_entity: input_boolean.light_automation_downstairs
  delay: 60
  daytimes:
    - { starttime: "05:30", name: morning, light: 5}
    - { starttime: "07:30", name: day, light: 100 }
    - { starttime: "20:30", name: evening, light: 30 }
    - { starttime: "22:30", name: night, light: 20 }
    - { starttime: "23:30", name: more_night, light: 1 }
  illuminance_threshold: 100
  illuminance: 
    - sensor.illuminance_dressing
  lights:
    - light.dressing
  motion:
    - binary_sensor.motion_dressing
  motion_event: state_changed
```

**Comment by thundergreen** [comment]
seems like it listens not only for state but also attributes maybe?

**Comment by thundergreen** [comment]
![image](https://user-images.githubusercontent.com/13320319/72473646-6b932580-37e7-11ea-8e9c-d4361d8e3905.png)

**Comment by thundergreen** [comment]
hmm there's nothing really  i will observe what's happening and revert

**Comment by benleb** [comment]
okay, i digged a little into this. the difference to the xiaomi sensors is that they will emit an event if they detect motion - even if they are already "on" -> this is used in automoli to refresh the countdown timer which will switch of the lights eventually.

without such an event, we have to do something new... we listen for on/off state of the motion sensors (on = motion detected). if a sensors changes to on, we switch on the light. and to switch it off, we listen for the change to "off", check if all other motion sensors in the room are also "off" and if so, we start the countdown timer... I am currently testing this a little :D

**Comment by benleb** [comment]
@thundergreen are you sometimes around in the home assistant or appdaemon slack or something?

**Comment by thundergreen** [comment]
hi! i am on discord if needed :) and your statement is exactly the behaviour needed for this component and i am open to test. just write me on discord. my name there is thundergreen as well

**Comment by benleb** [comment]
okay, sent you a version to test 👍

**Comment by thundergreen** [comment]
@benleb wherre? :P

**Comment by benleb** [comment]
thundergreen on home assistant discord... :D but np...

code here: https://gist.github.com/benleb/663f3077ef9b5353f168670fc4d48227

config used (motion event removed, motion_state_on/off added):
```
office:
  module: automoli
  class: AutoMoLi
  disable_switch_entity: input_boolean.automoli
  room: buro
  delay: 200
  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - {starttime: "05:30", name: morning, light: 0}
    - {starttime: "07:15", name: day, light: "scene.of_work"}
    - {starttime: "17:30", name: evening, light: 70}
    - {starttime: "19:30", name: night, light: 0}
```
