### ISSUE TITLE
Dynamic start of night mode

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#37]
I am looking for a way to enable a night mode (like reduced hue) based on an input Boolean that I activate with a switch, for example.

The use case is like this: when going to bed, I switch on night mode and I expect AutoMoLi to activate a specific scene.

Is this already possible?

**Comment by freekeys** [comment]
+1!

**Comment by Iskenof** [comment]
+1

**Comment by benleb** [comment]
implemented as "alpha" in https://github.com/benleb/ad-automoli/commit/b0e22f9a286a979834279a1e2fa64b217850e5b8

tested with this config:
```yaml
diningroom:
  module: automoli
  class: AutoMoLi
  disable_switch_entities: [input_boolean.automoli]
  room: esszimmer
  delay: 300
  night_mode:
    entity: input_boolean.automoli_night_mode
    light: 10
  ...
```

`entity` is a (single) boolean entity representing the night_mode state: if `entity` is `on` -> `night_mode` is `on`
`light` works like the `light` in daytimes and wants an integer (brightness percentage) or a string (scene)

please test and tell me what you think :)
