### ISSUE TITLE
Dynamic daytimes

### ISSUE THREAD

**Issue by freekeys** [benleb/ad-automoli#40]
I'd love to have the daytime adjustments be dynamic based on sunset time (e.g. sunset-1hr, sunset-30mins etc etc)

**Comment by oscfor** [comment]
Yeah, that would be great. Up in the north we have great difference in sunrise during the year.

**Comment by sivastola** [comment]
I'd love to see something like this as well.
Here is how I used it in automations.yaml before I moved to automoli
```
id: aqara_motion2_an
  alias: BWM Aqara Motion2 Flurlicht An
  trigger:
  - entity_id: group.motiongroupflurlicht
    platform: state
    to: 'on'
  action:
  - entity_id: light.flurlicht
    service: homeassistant.turn_on
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: -01:00:00
    - condition: sun
      before: sunrise
      before_offset: 01:00:00
```
the important part is the condition-part
maybe it helps
