### ISSUE TITLE
AutoMoli not working anymore .. nothing in logs

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#47]
Hello I used AutoMoli and was fan until today :P Well my setup stopped working. I changed the config to latest information in the release notes but still nothing work no error thrown. 

Here is my config maybe you can have a quick look:

```
entrance:
  module: automoli
  class: AutoMoLi
  room: Entrance
  disable_switch_entities: 
    - input_boolean.automoli_general
  delay: 10
  daytimes:
    - { starttime: "05:30", name: morning, light: 0 }
    - { starttime: "07:20", name: day, light: 1 }
    - { starttime: "20:30", name: evening, light: 1 }
    - { starttime: "22:30", name: night, light: 0 }
    - { starttime: "23:30", name: more_night, light: 0 }
  illuminance_threshold: 29
  illuminance: 
    - sensor.average_luminance_in_the_house
  lights:
    - light.entrance
  motion:
    - binary_sensor.multisenor_entrance_motion
  motion_state_on: "on"
  motion_state_off: "off"
```

all entities are there and work correctly Any hint here?
