### ISSUE TITLE
Make disable_switch_entities and disable_switch_states more flexible

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#54]
First of all thank you for your add-on! Its great and makes my motion sensor work perfectly! 

I have a feature suggestion (maybe its already possible and I am just to stupid).

I would like to have a switch "Motions Sensors Room X", when the switch is on automoli should do its job. This is already possible of course but I also have a TV in the same room, where the `disable_switch_states` would be the opposite. So automoli should stop doing its job either when the TV is `on` or when the motion sensor input boolean is `off`.

Maybe a configuration like this would be possible?
```
room_motionsensor:
  module: automoli
  class: AutoMoLi
  room: room1
  #### Interesting bit start ####
  disable_switch_entities:
    - switch.fernseher:
      disable_switch_states: "on"
    - input_boolean.motionsensor:
      disable_switch_states: "off"
   #### Interesting bit end ####
  delay: 300
  daytimes:
    - { starttime: "05:30", name: morning, light: 50 }
    - { starttime: "08:30", name: day, light: 100 }
    - { starttime: "00:00", name: night, light: 35 }
  motion_state_on: "on"
  motion_state_off: "off"
  motion:
    - binary_sensor.room_motion
  lights:
    - light.room_decke_1
    - light.room_decke_2
    - light.room_decke_3
```

**Comment by benleb** [comment]
Hmm, I think with automoli itself that would not work currently. Your configuration would probably lead to the question if that's an "and" or "or" condition and we would end up implementing both :D

But maybe there is a cooler way that makes it immediately working... What about a template binary_sensor in home assistant?
They already have a fully implemented templating system with conditions and everything else... something like this (untested, but you get the point):

```yaml
binary_sensor:
  - platform: template
    sensors:
      automoli_combined_switch:
        value_template: "{{ (is_state('switch.fernseher', 'on') and is_state('input_boolean.automoli', 'off')) }}"
```

Or are there any reasons this wouldn't work?
