### ISSUE TITLE
Feature request: night_mode

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#55]
Instead of using daytimes a night_mode would be great! I have an input boolean called `night_mode` when its on I would like the lights to turn on with a brightness set for night mode if its off use the default.

An configuration idea / example:
```yaml
xyz:
  module: automoli
  class: AutoMoLi
  room: xyz
  delay: 180
  night_mode_entity: 'input_boolean.night_mode'
  night_mode_brightness: 100
  night_mode_scene: scene.bla
  brightness: 255
  motion:
    - binary_sensor.xyz
  lights:
    - light.xyz
```

Even cooler would be if lights would also dimm up if night mode is disabled while the light is already on.

There also is this https://github.com/apop880/Night-Mode maybe it could be used if when not configuring any daytimes it would not use defaults and instead just toggle the light with the current brightness. apop880`s  night mode can already be kind of used by setting all daytimes to 100% brightness but the lights will flash up before being dimmed down then.

**Comment by benleb** [comment]
Sounds cool! I will look how to implement this, may take some days as there is a little backlog of issues currently 😅

**Comment by paviro** [comment]
No worries! Thank you for considering it!

**Comment by paviro** [comment]
Being able to combine it with daytimes would be even more awesome! So we can use different scenes (for coloured lights per daytime) but only dime the lights when night mode aka going to sleep is enabled.

**Comment by paviro** [comment]
(Just noticed this is kind of a duplicate of #37 - sorry about that.

**Comment by paviro** [comment]
Hi @benleb any update on this or ways I can help implementing it? I tried before but it was a bit over my head :D

**Comment by benleb** [comment]
sorry :/

implemented as "alpha" in https://github.com/benleb/ad-automoli/commit/b0e22f9a286a979834279a1e2fa64b217850e5b8

tested with this config:
```yaml
diningroom:
  module: automoli
  class: AutoMoLi
  disable_switch_entities: [input_boolean.automoli]
  room: esszimmer
  delay: 300
  night_mode:
    entity: input_boolean.automoli_night_mode
    light: 10
  ...
```

`entity` is a (single) boolean entity representing the night_mode state: if `entity` is `on` -> `night_mode` is `on`
`light` works like the `light` in daytimes and wants an integer (brightness percentage) or a string (scene)

please test and tell me what you think :)
