### ISSUE TITLE
Automobile shouldn’t turn lights of when disable_switch_entity is on

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#57]
🙄 **Is your feature request related to a problem? Please describe.**
I have the following use case: I set disable_switch_entity to a media player and have an automation that dims the lights when playing something back. When playback is paused the lights get dimmed back up. Problem is automoli still disabled the dimmed down lights when there is no motion even when it’s disabled by the media player state.

😍 **Describe the solution you'd like**

disable_switch_entity should not only not turn lights on but also not off.

When the switch is disabled automoli should take over again when no motion is detected however.

**Edit:**
This also happens when manually enabling lights (see picture).
<img width="991" alt="sdfsdfjkfsd" src="https://user-images.githubusercontent.com/992826/102716095-edce7880-42d9-11eb-8441-28cd10c9ba69.png">

**Edit 2:**
This can be solved by using the new `only_own_events: true`.

**Comment by paviro** [comment]
Solved it by adding the tv as a motion sensor, as the TV being on can be considered as someone is precent. 
```yaml
motion_state_on: "on"
  motion_state_off: "off"
  motion:
    - binary_sensor.wohnzimmer_bewegung
    - binary_sensor.kuche_bewegung
    - binary_sensor.wohnzimmer_treppe_bewegung
    - binary_sensor.flur_eg_bewegung
    - input_boolean.wohnzimmer_presence_overwrite
    - switch.fernseher
```

Feel free to close this issue, I will keep it open as this should probably still be the default?
