### ISSUE TITLE
Daytimes mixing scenes and light percentages

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#59]
🙄 **Is your feature request related to a problem? Please describe.**
I am currently using a mixture of scenes and light brightness for my daytimes. If a light is enabled after 10pm for example the scene `badezimmer_entspannend` is triggered after 0am the same scene is continued being used just dimmer. If the light isn't triggered between 10pm and 0am however the scene before `badezimmer_abend` will be used.

😍 **Describe the solution you'd like**
Add an option to use the last specified scene (with adjusted brightness) when using only light brightness.

🖼️ **Example/See here!** 
```yaml
badezimmer_bewegungsmelder:
  module: automoli
  class: AutoMoLi
  room: Badezimmer
  delay: 180
  daytimes:
    - { starttime: "05:00", name: morning, light: 30 }
    - { starttime: "09:30", name: morning, light: "scene.badezimmer_normal" }
    - { starttime: "18:30", name: morning, light: "scene.badezimmer_abend" }
    - { starttime: "22:00", name: night, light: "scene.badezimmer_entspannend" }
    - { starttime: "00:00", name: night, light: 50 }
  
  motion_state_on: "on"
  motion_state_off: "off"
  motion:
    - binary_sensor.badezimmer_bewegung
    - binary_sensor.flur_og_bewegung
    
  dim:
    method: transition
    seconds_before: 15
```
