### ISSUE TITLE
KeyError: 'light_setting'

### ISSUE THREAD

**Issue by jfrux** [benleb/ad-automoli#8]
Sorry for so much all at once... just don't want to forget to post these! 
Not sure what's causing it... I am using switches and not lights.  I have a mixture of switches and lights in the "lights" list... maybe that's the issue?
or maybe we need a "switches" property.
I'll can try to help fix if you want.

```
2020-01-13 19:07:28.408780 WARNING ellys_bedroom: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/appdaemon/threading.py", line 793, in worker
    funcref(args["event"], data, args["kwargs"])
  File "/conf/apps/automoli/automoli.py", line 233, in motion_event
    self.lights_on()
  File "/conf/apps/automoli/automoli.py", line 258, in lights_on
    if isinstance(self.active["light_setting"], str):
KeyError: 'light_setting'
```

**Comment by benleb** [comment]
yes sorry! thats a really stupid bug already mentioned in #5 

a quick-fix is already in master (needs python >=3.8), a proper fix and a release including it will come in the next hours!

**Comment by jfrux** [comment]
Oh wow! Did not realize it was the same bug!
I posted both issues... shame on me!  Hah!  Thanks dude.

Love what you're doing... I have lots of ideas for how I can make use of this.  Thanks for making this easier for everyone!

**Comment by benleb** [comment]
ah maybe its not completely the same but a variant... can you show me your config? Switches should already work, I also use it. Example of my config
![image](https://user-images.githubusercontent.com/512997/72347741-1537c100-36d9-11ea-9ee9-30fadefd0cae.png)

**Comment by jfrux** [comment]
``` yaml
first_floor_bathroom:
  module: automoli
  class: AutoMoLi
  room: first_floor_bathroom
  delay: 600
  motion_event: state_changed
  daytimes: []
  lights:
    - switch.first_floor_bathroom_light
    - switch.first_floor_bathroom_fan
  motion:
    - binary_sensor.first_floor_bathroom_motion_sensor

spencers_bedroom:
  module: automoli
  class: AutoMoLi
  room: spencers_bedroom
  delay: 1800
  motion_event: state_changed
  daytimes: []
  lights:
    - switch.spencers_ceiling_light
    - switch.spencers_ceiling_fan
    - switch.spencers_closet_light
    - switch.spencers_box_fan
  motion:
    - binary_sensor.spencers_room_motion

ellys_bedroom:
  module: automoli
  class: AutoMoLi
  room: ellys_bedroom
  delay: 1800
  motion_event: state_changed
  daytimes: []
  lights:
    - switch.ellys_ceiling_light
    - switch.ellys_ceiling_fan
    - light.ellys_lamp
    - switch.ellys_closet_light
  motion:
    - binary_sensor.ellys_room_motion

upstairs_hallway:
  module: automoli
  class: AutoMoLi
  room: upstairs_hallway
  delay: 1800
  motion_event: state_changed
  daytimes: []
  lights:
    - switch.upstairs_hallway_light
    - switch.kids_bathroom_light
    - switch.kids_bathroom_fan
  motion:
    - binary_sensor.upstairs_hallway_motion
```
