### ISSUE TITLE
Automoli broken?

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#88]
😩 **Describe the issue/bug**
I dint know what changed or what i did wrong but I just got this error.
😒 **Expected behavior**
That it works :) 
🎛️ **Configuration**
```yaml
garage:
  module: automoli
  class: AutoMoLi
  room: Garage
  disable_switch_entities:
    - input_boolean.automoli_garage
    - input_boolean.automoli_general
  delay: 180
  illuminance_threshold: 25
  illuminance:
    - sensor.average_luminance_downstairs
  daytimes:
    - { starttime: "05:30", name: morning, light: 100 }
    - { starttime: "06:45", name: day, light: 100 }
    - { starttime: "08:00", name: day, light: 100 }
    - { starttime: "10:00", name: day, light: 100 }
    - { starttime: "17:30", name: more_day, light: 100 }
    - { starttime: "20:30", name: evening, light: 100 }
    - { starttime: "21:30", name: night, light: 100 }
    - { starttime: "22:30", name: more_night, light: 100 }
  motion:
    - binary_sensor.door_window_sensor_158d00019daf53
    - binary_sensor.garage_person_motion
    - binary_sensor.motion_sensor_158d000121564c
    - binary_sensor.door_window_sensor_158d00019daf42
  motion_state_on: "on"
  motion_state_off: "off"
  lights:
    - light.garage
```

🧠 **System**
 - AppDaemon: **[e.g. 4.0.5]**
   -  running mode: **[e.g. virtualenv, hassio-plugin, docker]**
 - Home-Assistant: **[e.g. 0.118.3, 0.119.0b0]**
   -  running mode: **[e.g. virtualenv, hassio, docker]**
 - Python: **[e.g. 3.8.6, 3.9]**

🗒️ **Logs** 

```log
2021-11-30 23:28:13.704980 WARNING garage: Unexpected error in worker for App garage:
2021-11-30 23:28:13.705338 WARNING garage: Worker Ags: {'id': 'dcc5d7f1d44b4907a2316b35970acc1d', 'name': 'garage', 'objectid': '77411ea9894d4b819ee1c6110e565fb5', 'type': 'state', 'function': <bound method AutoMoLi.motion_detected of <automoli.AutoMoLi object at 0x7f11eee17e20>>, 'attribute': 'state', 'entity': 'binary_sensor.door_window_sensor_158d00019daf53', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 11, 'kwargs': {'new': 'on', '__thread_id': 'MainThread'}}
2021-11-30 23:28:13.705589 WARNING garage: ------------------------------------------------------------
2021-11-30 23:28:13.705942 WARNING garage: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 570, in motion_detected
    await self.motion_event("state_changed_detection", data, kwargs)
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 599, in motion_event
    await self.lights_on()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 840, in lights_on
    f"{float(await self.get_state(sensor)) = }",  # type:ignore
TypeError: float() argument must be a string or a number, not 'NoneType'
2021-11-30 23:28:13.706200 WARNING garage: ------------------------------------------------------------```

🧁 **Additional context**
Add any other context about the problem here.
